doctrine:
    dbal:
#        url: '%env(resolve:DATABASE_URL)%'
        driver: pdo_pgsql
        host: 127.0.0.1
        port: 5432
        dbname: db_tarkett
        user: db_user
        password: db_pass
        charset: utf8
        server_version: '12.3'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App



# bin/console doctrine:database:create
# bin/console doctrine:schema:create